version: '2.2'
services:
  ubuntuweb71:
    image: orangehrm/orangehrm-environment-images:dev-7.1-ubuntu-18.04
    ports:
      - "9100:443"
    volumes:
      - ./html:/var/www/html
      - ./custom-compose/config/ubuntuweb71/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./custom-compose/config/ubuntuweb71/apache2/cert:/etc/apache2/cert
      - ./custom-compose/config/ubuntuweb71/apache2/conf.d/apache2.conf:/etc/apache2/apache2.conf
      - ./custom-compose/logs/apache_logs/ubuntuweb71:/var/log/apache2
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.171
    restart: always
    container_name: dev_web_71_ubuntu